layout_spectrum: 0.24224908486939967
typography_spectrum: 0.0024708614218980074
color:
  brandStrength: 0.10782814980484545
  lightness: 0.045852335169911385
  saturation: 0.47803664952516556
  rhythmicContrast: 0.8456205397378653
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
author:
  name: Jonathan Puritz
  email: jpuritz@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5dc3fe92-6703-4192-aa65-3df952c1fe26.png
name: MarineEvoEco.com
navigation:
  - name: About Me
    id: 08b0f8b7-b43c-428a-95b9-58f8844533ac
    type: content
  - name: CV
    id: 8113dc93-ead9-4557-913f-b7ecd6660e74
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/80b2ba7e-b26f-49da-be58-ce4b2a72a3ae.png
title: 'Jonathan B. Puritz, PhD.'
description: Marine Evolutionary Ecologist
